<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PackageId>slafniy.LibMSPSharp</PackageId>
        <Authors>slafniy</Authors>
        <RepositoryUrl>https://github.com/slafniy/libmsp-sharp</RepositoryUrl>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <Version>0.0.6</Version>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <!-- For nuget packaging - place native lib preserving path -->
        <None Include="runtimes/linux-x64/native/libmsp.so">
            <Pack>true</Pack>
            <PackagePath>runtimes/linux-x64/native/libmsp.so</PackagePath>
        </None>

        <!-- For nuget packaging - add README -->
        <None Include="../README.md">
            <Pack>true</Pack>
            <PackagePath>/</PackagePath>
        </None>

        <!-- For nuget packaging - add LICENSE -->
        <None Include="../LICENSE.txt">
            <Pack>true</Pack>
            <PackagePath>/</PackagePath>
        </None>
    </ItemGroup>

</Project>
